name: 触发版本号更新
on:
  release:
    types: [published]

jobs:
  send-dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Repo Workflow
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          curl -X POST -H "Accept: application/vnd.github+json" \
               -H "Authorization: Bearer $GH_TOKEN" \
               -H "Content-Type: application/json" \
               -d "{\"event_type\": \"update-version\"}" \
               https://api.github.com/repos/Class-Widgets/cw-interim-site/dispatches