name: 生成 Changelog 并发布版本

on:
  workflow_call:
    inputs:
      runid:
        required: true
        type: string

jobs:
  generate-changelog-and-release:
    name: 生成 Changelog 并发布版本
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get previous tag
        uses: younited/get-previous-tag-action@v1.0.0
        id: getprevtag

      - name: Generate a changelog
        id: generate-changelog
        uses: orhun/git-cliff-action@v3
        with:
          config: cliff.toml
          args: --verbose $PREV..$TAG
        env:
          PREV: ${{ steps.getprevtag.outputs.previous-tag }}
          TAG: ${{ github.ref_name }}
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}
      - name: Prepare release
        run: mkdir release
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: release
          run-id: ${{ github.event.workflow_run.id }}
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: release/*
          body_path: CHANGELOG.md
          draft: true
